export enum ETanksGameImgName {
	START_SCREEN   = "START_SCR",
	EAGLE          = "eagle.png",
	LEAVES         = "leaves.png",
	SMALL_WALL_1   = "small_wall_1.png",
	SMALL_WALL_2   = "small_wall_2.png",
	SMALL_WALL_3   = "small_wall_3.png",
	SMALL_WALL_4   = "small_wall_4.png",
	WALL           = "wall.png",
	WATTER         = "watter.png",
	BONUS_IMMORTAL = "bonus_immortal.png",
	BONUS_LIVE     = "bonus_live.png",
	BONUS_SLOW     = "bonus_slow.png",
	BONUS_SPEED    = "bonus_speed.png",
	BULLET         = "BULLET.png",
	ENEMY_BULLET   = "ENEMY_BULLET.png",
	LOADER_BAR     = "LOADER_BAR.png",
	LOADER_BG      = "LOADER_BG.png",
	START_BUTTON   = "START_BUTTON.png",
	SCORES_BUTTON  = "SCORES_BUTTON.png",
	USER_TANK      = "USER_TANK.png",
	TANK_BLUE      = "TANK_BLUE.png",
	TANK_RED       = "TANK_RED.png",
	TANK_WHITE     = "TANK_WHITE.png"
}
