export enum ETanksGameCommonName {
	CONTAINER          = "container",
	CANVAS             = "canvas",
	TEXTURES_CONTAINER = "Textures container",
	START_BUTTON       = "Start Button",
	HIGH_SCORE_BUTTON  = "High score Button",
	BULLETS_CONTAINER  = "Bullets container",
	USERS_TANK         = "Users tank",
	TANKS_FIELD        = "Tanks field",
	BACKGROUND         = "Background",
	SOUNDS             = "SOUNDS",
	SOUNDS_SPRITES     = "SOUNDS_SPRITES",
	BOT_TANK_WHITE     = "BOT_TANK_WHITE",
	BOT_TANK_BLUE      = "BOT_TANK_WHITE",
	BOT_TANK_RED       = "BOT_TANK_WHITE",
	SMALL_WALL         = "SMALL_WALL",
	TANK               = "TANK",
	WALL               = "WALL",
	EAGLE              = "EAGLE"
}
