export enum ETanksGameCommandName {
	DRAW_START_SCREEN     = "DRAW_START_SCREEN",
	LOAD_BOOT_RESOURCES   = "LOAD_RESOURCES",
	LOAD_IMG              = "LOAD_IMG",
	LOAD_SOUNDS           = "LOAD_SOUNDS",
	UPDATE_SCENE          = "UPDATE_SCENE",
	ADD_MENU_UI_LISTENERS = "ADD_MENU_UI_LISTENERS",
	FRAME_UPDATE          = "FRAME_UPDATE",
	ADD_BULLET_TO_SCENE   = "ADD_BULLET_TO_SCENE"
}
